M48
; DRILL file {KiCad (6.0.8)} date Thu Oct 20 20:28:10 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-20T20:28:10+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X25.925Y-127.635
T2
X31.75Y-41.275
X31.75Y-142.24
X191.77Y-41.275
X191.77Y-142.24
T0
M30
